

AMD64_OBJECTS=\
 $(OBJ_PATH)\$O\vpd.obj \


_RES_FILE=$(OBJ_PATH)\$O\vpd.res
PRECOMPILED_INCLUDE_BASENAME=precomp.h




# lowercased
BASEDIR=c:\winddk\7600.16385.1
OBJECT_ROOT=c:\winddk\7600.16385.1
MAKEDIR_LOWERCASE=c:\winddk\7600.16385.1\src\print\vpd\vpd\vpd\src
MAKEDIR_RELATIVE_TO_BASEDIR=src\print\vpd\vpd\vpd\src
OBJ_PATH=c:\winddk\7600.16385.1\src\print\vpd\vpd\vpd\src
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
